name = "speedwayworld-blog"
compatibility_date = "2026-09-05" # Match today's date

[vars]
GITHUB_CLIENT_ID = "Ov23liKHoL66zhA0Awa9"

[assets]
directory = "./dist" # Astro automatically outputs compiled files here
