backend:
  name: github
  repo: bigo229/speedwayworld-blog
  branch: main
  base_url: https://speedwayworld-blog.bigo229.workers.dev
  auth_scope: repo
  proxy_url: /admin/api

media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Updated Date, name: updatedDate, widget: datetime, required: false }
      - { label: Hero Image, name: heroImage, widget: image, required: false }
      - { label: Author, name: author, widget: string, default: 'SpeedwayWorld WebTeam' }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Category, name: category, widget: string, required: false }
